# -*- coding: utf-8 -*-
"""add2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17H7GeXLk5E9wbHMdY1tS4bPDVAQNMKMj
"""
 
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from gtts import gTTS
import os
import uuid
import gradio as gr
import whisper

# Load and prepare dataset
df = pd.read_csv("kamaraj_college_faq.csv")
df.dropna(inplace=True)

label_encoder = LabelEncoder()
df["Answer_Label"] = label_encoder.fit_transform(df["Answer"])

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["Question"])
y = df["Answer_Label"]

model = LogisticRegression()
model.fit(X, y)

# Text-to-speech using gTTS
def speak_text(text):
    tts = gTTS(text=text, lang='en')
    filename = f"audio_{uuid.uuid4().hex}.mp3"
    tts.save(filename)

    try:
        if os.name == "nt":  # Windows
            os.system(f"start {filename}")
        elif os.uname().sysname == "Darwin":  # macOS
            os.system(f"afplay {filename}")
        else:  # Linux
            os.system(f"mpg123 {filename}")
    except Exception as e:
        print("Audio playback failed:", e)

# Load Whisper model for audio transcription
whisper_model = whisper.load_model("base")

# Main chatbot function
def chatbot(audio=None, text=None):
    if audio:
        result = whisper_model.transcribe(audio)
        user_input = result["text"]
    elif text:
        user_input = text
    else:
        return "❗ Please provide a question."

    # Predict the answer
    vec = vectorizer.transform([user_input])
    prediction = model.predict(vec)[0]
    answer = label_encoder.inverse_transform([prediction])[0]

    # Speak the answer
    speak_text(answer)

    return f"🗣️ You asked: {user_input}\n✅ Answer: {answer}"

# Gradio Interface
iface = gr.Interface(
    fn=chatbot,
    inputs=[
        gr.Audio(sources=["microphone"], type="filepath", label="🎤 Speak your question"),
        gr.Textbox(lines=2, placeholder="Or type your question here", label="📝 Text question")
    ],
    outputs="text",
    title="🎓 Kamaraj College FAQ Chatbot",
    description="Ask your question by voice or text. It will speak back the answer!"
)

iface.launch()
