# -*- coding: utf-8 -*-
"""add3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TNPv57ypZZbgHos7pjETNgjC2jLD5lmp
"""



pip install gradio gTTS pygame openai-whisper pandas scikit-learn

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from gtts import gTTS
import pygame
import gradio as gr
import whisper
import os
import time

# Load and train the model
df = pd.read_csv("kamaraj_college_faq.csv")
df.dropna(inplace=True)

le = LabelEncoder()
df["Answer_Label"] = le.fit_transform(df["Answer"])

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["Question"])
y = df["Answer_Label"]

model = LogisticRegression()
model.fit(X, y)

# Load Whisper model for voice-to-text
whisper_model = whisper.load_model("base")

# Text-to-speech using gTTS and pygame
def speak_text(text):
    filename = "answer.mp3"
    tts = gTTS(text=text, lang="en")
    tts.save(filename)

    pygame.mixer.init()
    pygame.mixer.music.load(filename)
    pygame.mixer.music.play()
    while pygame.mixer.music.get_busy():
        time.sleep(0.1)
    pygame.mixer.music.unload()
    os.remove(filename)

# Chatbot logic
def chatbot(audio=None, text=None):
    # Convert audio to text if present
    if audio:
        result = whisper_model.transcribe(audio)
        user_input = result["text"]
    elif text:
        user_input = text
    else:
        return "❗ Please provide a question by voice or text."

    # Predict the answer
    vec = vectorizer.transform([user_input])
    prediction = model.predict(vec)[0]
    answer = le.inverse_transform([prediction])[0]

    # Speak the answer
    speak_text(answer)

    return f"🗣️ You asked: {user_input}\n✅ Answer: {answer}"

# Gradio Interface
iface = gr.Interface(
    fn=chatbot,
    inputs=[
        gr.Audio(sources=["microphone"], type="filepath", label="🎤 Speak your question"),
        gr.Textbox(lines=2, placeholder="Or type your question here", label="📝 Text question")
    ],
    outputs="text",
    title="🎓 Kamaraj College FAQ Chatbot",
    description="Ask a question by voice or text. It will answer and speak the reply back to you.",
)

iface.launch()